# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'
- script: dotnet restore
- task: DotNetCoreCLI@0
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@1
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Run the unit test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/DotNetCoreHelloWorld/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: False
    projects: "" 
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True    
- task: AzureRmWebAppDeployment@3
  displayName: 'Deploy code to webapp'
  inputs:
    azureSubscription: 'minadote'
    WebAppName: 'minadot10086'
    Package: $(System.ArtifactsDirectory)/*.zip            


