# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300' # replace this value with the version that you need for your project
- script: dotnet restore
- task: DotNetCoreCLI@0
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@1
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Run the unit test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'        
- task: PublishBuildArtifacts@1
- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: 'my azureSubscription'
    WebAppName: 'minadotnethello'
    Package: $(System.ArtifactsDirectory)/**/*.zip


